name: terratest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create Kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          cluster_name: kind-test
          config: k8s/kind/cluster.yaml
      - name: Install ingress controller
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
      - name: Wait for ingress controller to be ready
        run: kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
      - name: Terratest
        run: make terratest
